# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bs_even_C <- function(time, nk) {
    .Call('_bayesFDA_bs_even', PACKAGE = 'bayesFDA', time, nk)
}

.g2g_fda <- function(curves, lasts, time, p, niter, nburn) {
    .Call('_bayesFDA_g2g_fda', PACKAGE = 'bayesFDA', curves, lasts, time, p, niter, nburn)
}

.cov_fda <- function(curves, X, time, p, niter, nburn) {
    .Call('_bayesFDA_cov_fda', PACKAGE = 'bayesFDA', curves, X, time, p, niter, nburn)
}

